import React from "react";
import Head from "next/head";

const Heads = (props) => {
	return (
		<>
			<Head>
				<title>About</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='keywords'
					content='javascript, reactjs, css, nextjs, huntingcoders, hunting coder blog,'
				/>
				<link rel='icon' href='/nextjs-icon.png' />
			</Head>
		</>
	);
};
export default Heads;